overrides:
  - files: '**/__tests__/*.test.ts'
    rules:
      '@typescript-eslint/no-explicit-any': off
    env:
      jest: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint

parser: '@typescript-eslint/parser'

env:
  node: true
  es6: true

parserOptions:
  sourceType: module

rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-explicit-any': off
