name: Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 14]
    name: Node v${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Install node v${{ matrix.node_version }}
        with:
          node-version: ${{ matrix.node_version }}
      - uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn -s test
